---
title: "Data Translation Project"
format: html
editor: visual
---

```{r}
# Load Necessary Packages
library(lubridate)
library(stringr)
library(tidyverse)
library(vtable)
library(fixest)
library(readr)
library(dplyr)
library(rio)
library(ipumsr)
```

```{r}
# Load Data
ddi <- read_ipums_ddi("cps_00002.xml")
Translation.data <- read_ipums_micro(ddi)

# Show only rows from 2015 and beyond 
Translation.data$YEAR <- as.numeric(Translation.data$YEAR)

Translation.data <- Translation.data[Translation.data$YEAR >= 2015, ]

# Filter out ASECFLAG data, so that data is cleaner. 
Translation.data <- Translation.data %>% filter(is.na(ASECFLAG))

# Filter data so that only rows where EMPSTAT is equal to 10 (employed) or 21 (unemployed) are included. 
Translation.data <- Translation.data %>% filter(EMPSTAT %in% c(10, 21))
```

# 1) How has COVID affected the health of the retail Industry, as measured by employment?

```{r}
# Join indnames.csv and the Translation.data df
# Read in indnames.csv
indnames <- import('indnames.csv')

# Rename the IND column in Translation.data to ind so that we can join them, using names()[].
names(Translation.data)[20] <- "ind"

# Join Translation.data with indnames using the 'ind' column.
Translation.data <- 
  inner_join(Translation.data, indnames, by = "ind")
```

```{r}
# Join year and month columns together and format as date.
Translation.data <- Translation.data %>% mutate(Date.year.month = ym(paste0(YEAR, '/',MONTH)))

# Add a Cutoff Variable at 3.11.20 to indicate the WHO recognition of COVId as a global pandemic. # need to edit. 
Translation.data <- Translation.data %>% mutate(covid.pre.post = case_when(
  Date.year.month <= ym('2020/03') ~ "Before",
  Date.year.month > ym('2020/03') ~ "After"
))

# Create a variable that is centered around Date.year.month == "2020 03)
Translation.data <- Translation.data %>%
  mutate(Center.Date = Date.year.month - as.Date("2020-03-01"))

# Create character variable for employment. Employed = EMPSTAT == 10 | Unemployed = EMPSTAT == 21
Translation.data <- Translation.data %>% mutate(Employment.Status = case_when(
  EMPSTAT == 10 ~ "EMPLOYED",
  EMPSTAT == 21 ~ "UNEMPLOYED"
))

# Create binary variable for employment. Employed = EMPSTAT == 10 | Unemployed = EMPSTAT == 21
Translation.data <- Translation.data %>% mutate(Employment.Status.numeric = case_when(
  EMPSTAT == 10 ~ 1,
  EMPSTAT == 21 ~ 0
))

# Create a character variable for retail trade employee. Retail Employee = indname == 'Retail Trade' 
Translation.data <- Translation.data %>% mutate(Retail.Trade.Employee = case_when(
  indname == 'Retail Trade' ~ "TRUE",
  TRUE ~ "FALSE"
))

# Create new data frame with only individuals employed in retail
Retail.data <- Translation.data %>% 
  filter(Retail.Trade.Employee == "TRUE")
```

```{r}
# Visual for number of retail employees per month.
# Create data set that contains only Retail data: in "Retail Trade" and EMPSTAT == 10 and 21
Retail.data.visual <- Translation.data %>% filter(indname == "Retail Trade" & EMPSTAT %in% c(10, 21))

# Create a new column that contains a varible that counts the number of retail employees, per month. 
Retail.data.visual <- Retail.data.visual %>% group_by(Date.year.month) %>%
  mutate(count.EMPSTAT.10 = sum(EMPSTAT == 10),
         count.EMPSTAT.21 = sum(EMPSTAT == 21),
         )
# Clean so that there is only one observation per month.
Retail.data.visual <- Retail.data.visual %>% distinct(Date.year.month, covid.pre.post, .keep_all = TRUE)

# Graph data
Plot.point.1 <- ggplot(Retail.data.visual, aes(x = Date.year.month, y = count.EMPSTAT.10)) +
  geom_point(color = "blue") +
  geom_line() +
  geom_vline(xintercept = ym('2020/03'), color = "orange", linetype = "dashed") +
  theme_minimal() +
  labs(title = 'Employment in Retail Trade from 2019-2022', x = 'Date', y = 'Count of Retail Trade Employees')
Plot.point.1
```

```{r}
# Q1 Regression Model: RDD with fixed effects for industry.

# This model regresses Employment Status on the covid cutoff interacted with an indicator variable that takes a value of 1 if indname = Retail Trade, and 0 if not, and an interaction with the running variable, time, which has been centered around the cutoff date (2020/03).
# The model describes the effect of the covid cutoff on Employment status for the retail industry compared to all other industries in the data set. 

Q1.reg <- Translation.data %>%
feols(Employment.Status.numeric ~ covid.pre.post*I(indname == 'Retail Trade')*Center.Date)

Q1.reg2 <- Translation.data %>%
  filter(indname == 'Retail Trade') %>%
  feols(Employment.Status.numeric ~ covid.pre.post * Center.Date)


etable(Q1.reg)
etable(Q1.reg2)
```

```{r}
# The interaction term "covid.pre.postAfter x I(indname=="RetailTrade")TRUE" does not have a statistically significant effect at conventional levels (p > 0.05). This suggests that there is no strong evidence to support a differential effect of the post-COVID-19 period specifically for the "Retail Trade" industry compared to other industries. In other words, the impact of the post-COVID-19 period on the dependent variable is not significantly different between the "Retail Trade" industry and the other industries included in the analysis.

# The coefficient for "covid.pre.postAfter x I(indname=="RetailTrade")TRUE" (-0.0012, not statistically significant) suggests that there is no strong evidence to support a differential effect of the post-COVID-19 period specifically for the "Retail Trade" industry compared to the reference category. In other words, the impact of the post-COVID-19 period on the dependent variable does not significantly vary between the "Retail Trade" industry and other industries.

# sIn summary, the "I(indname =="RetailTrade")TRUE" coefficient represents the baseline effect of the "Retail Trade" industry compared to the reference category, while the "covid.pre.postAfter x I(indname=="RetailTrade")TRUE" coefficient captures the additional differential effect of the post-COVID-19 period specifically for the "Retail Trade" industry.
```

# 2)

```{r}.}
 # aggregrate comparison
Q2.reg <- Translation.data %>% 
  feols(Employment.Status.numeric ~ covid.pre.post*Retail.Trade.Employee*Center.Date)

feols(Employment.Status.numeric ~ covid.pre.post*I(indname == 'Retail Trade')*Center.Date)

indlevels = unique(Translation.data$indname)
indlevels = c('Retail Trade', indlevels[indlevels != 'Retail Trade'])
Translation.data <- Translation.data %>%
  mutate(indname = factor(indname, levels = indlevels)) %>%
  mutate(covid.pre.post = factor(covid.pre.post, levels = c('Before','After')))

  # Individual Comparison
feols(Employment.Status.numeric ~ indname, Translation.data)

Q2.reg2 <- Translation.data %>% 
feols(Employment.Status.numeric ~ indname*Center.Date*covid.pre.post)

# specify retail as reference group with i() 

etable(Q2.reg2, keep = 'covid.pre.post')
```

```{r}
# Visual for number of employees per month, by industry. 
# data set containing EMPSTAT == c(10,21) for all categories
Industry.data.visual <- Translation.data %>% filter(EMPSTAT %in% c(10, 21))

Industry.data.visual <- Industry.data.visual %>% group_by(Date.year.month, indname) %>%
  mutate(count.EMPSTAT.10 = sum(EMPSTAT == 10),
         count.EMPSTAT.21 = sum(EMPSTAT == 21),
         )

Industry.data.visual <- Industry.data.visual %>% distinct(Date.year.month, covid.pre.post, .keep_all = TRUE)

# Graph data
Plot.point.2 <- ggplot(Industry.data.visual, aes(x = Date.year.month, y = count.EMPSTAT.10, color = indname)) +
  geom_point() +
  geom_line() +
  geom_vline(xintercept = ym('2020/03'), color = "orange", linetype = "dashed") +
  theme_minimal() +
  labs(title = 'Employment from 2019-2022', x = 'Date', y = 'Count of Employees')
Plot.point.2
```

# 3) 

```{r}

```
